from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '0da12268f7db'
down_revision = '5597947f4337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('my_table', 'latitude',
                    existing_type=sa.String(),
                    type_=sa.Float(),
                    existing_nullable=True)
    op.alter_column('my_table', 'longitude',
                    existing_type=sa.String(),
                    type_=sa.Float(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Resource', 'latitude',
                    existing_type=sa.Float(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('Resource', 'longitude',
                    existing_type=sa.Float(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###
