"""update lat/lng to float

Revision ID: 534599f54f2b
Revises: bf80e3a1a69d
Create Date: 2023-09-30 13:23:14.475849

"""

from alembic import op
import sqlalchemy as sa
from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
import json
from src.app import app
from src.models import Resource, Offering, Schedule, db
from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context

revision = '534599f54f2b'
down_revision = 'bf80e3a1a69d'


def upgrade():
    op.execute(
        '''UPDATE "Resource" SET latitude=24.681678475660995 WHERE latitude='';''')
    op.execute(
        '''UPDATE "Resource" SET longitude=84.99154781534179 WHERE longitude='';''')

    op.execute(
        '''ALTER TABLE "Resource" ALTER COLUMN latitude TYPE DOUBLE PRECISION USING (latitude::double precision)''')
    op.execute(
        '''ALTER TABLE "Resource" ALTER COLUMN longitude TYPE DOUBLE PRECISION USING (longitude::double precision)''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Resource', 'latitude',
                    existing_type=sa.Float(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('Resource', 'longitude',
                    existing_type=sa.Float(),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###
