"""empty message

Revision ID: 08e33345a353
Revises: 4e647030cf53
Create Date: 2024-03-20 09:48:09.241738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e33345a353'
down_revision = '4e647030cf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FavoriteOfferings')
    op.drop_table('Rating')
    op.drop_table('Drop')
    op.drop_table('Offering')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Offering',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Offering_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('offering_type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Offering_pkey')
    )
    op.create_table('Drop',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Drop_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('identification', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Drop_pkey')
    )
    op.create_table('Rating',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Rating_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('rating_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], name='Rating_resource_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Rating_pkey')
    )
    op.create_table('FavoriteOfferings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"FavoriteOfferings_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='FavoriteOfferings_pkey')
    )
    # ### end Alembic commands ###
