"""empty message

Revision ID: 190cc1499b49
Revises: 08e33345a353
Create Date: 2024-10-23 05:27:51.380194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190cc1499b49'
down_revision = '08e33345a353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###
