"""empty message

Revision ID: 315ea5f2cba1
Revises: a94008a9b2e2
Create Date: 2025-03-16 12:15:23.117384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315ea5f2cba1'
down_revision = 'a94008a9b2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
