"""empty message

Revision ID: 4e647030cf53
Revises: 3d5f222a281f
Create Date: 2024-03-19 11:35:37.695219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e647030cf53'
down_revision = '3d5f222a281f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resourceId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['userId'], ['id'])
        batch_op.create_foreign_key(None, 'Resource', ['resourceId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resourceId')

    # ### end Alembic commands ###
