"""empty message

Revision ID: 664a9286157d
Revises: 2ee82b1be536
Create Date: 2025-03-15 21:18:53.661400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664a9286157d'
down_revision = '2ee82b1be536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ResourceUsers',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('resource_id', 'user_id')
    )
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('ResourceUsers')
    # ### end Alembic commands ###
