"""Add approved column to Comment

Revision ID: 6a2f01e83472
Revises: 315ea5f2cba1
Create Date: 2025-03-16 12:28:50.314978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2f01e83472'
down_revision = '315ea5f2cba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
