"""empty message

Revision ID: 712fd0b1a1b7
Revises: c34b05ae25dd
Create Date: 2024-11-11 14:53:02.899228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712fd0b1a1b7'
down_revision = 'c34b05ae25dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
