"""Renaming ResourceUsers to resource_users

Revision ID: 8cc2534c3b28
Revises: f7fcd8c43943
Create Date: 2025-03-15 21:32:58.709360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc2534c3b28'
down_revision = 'f7fcd8c43943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ResourceUsers',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'user_id')
    )
    op.drop_table('resource_users')
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('resource_users',
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], name='ResourceUsers_resource_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='ResourceUsers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'user_id', name='ResourceUsers_pkey')
    )
    op.drop_table('ResourceUsers')
    # ### end Alembic commands ###
