"""empty message

Revision ID: a6a02492195c
Revises: 190cc1499b49
Create Date: 2024-11-08 16:23:33.553799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6a02492195c'
down_revision = '190cc1499b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_value', sa.Integer(), nullable=True))
        batch_op.alter_column('comment_cont',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=280),
               existing_nullable=False)
        batch_op.drop_constraint('Comment_parentId_fkey', type_='foreignkey')
        batch_op.drop_column('parentId')

    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Comment_parentId_fkey', 'Comment', ['parentId'], ['id'])
        batch_op.alter_column('comment_cont',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.drop_column('rating_value')

    op.drop_table('Rating')
    # ### end Alembic commands ###
