"""Added approved column to Comment table

Revision ID: a94008a9b2e2
Revises: 25fad80fe367
Create Date: 2025-03-16 12:09:48.787115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94008a9b2e2'
down_revision = '25fad80fe367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
