"""Fix Many-to-Many Relationship

Revision ID: c284da245c50
Revises: 6b57faddd460
Create Date: 2025-03-15 22:40:29.490305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c284da245c50'
down_revision = '6b57faddd460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('resource_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_users', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('Resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
