"""empty message

Revision ID: c34b05ae25dd
Revises: a6a02492195c
Create Date: 2024-11-08 17:48:35.807923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34b05ae25dd'
down_revision = 'a6a02492195c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rating',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Rating_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], name='Rating_resource_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Rating_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Rating_pkey')
    )
    # ### end Alembic commands ###
