"""empty message

Revision ID: c51be90ce862
Revises: 
Create Date: 2023-11-23 17:36:30.925188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51be90ce862'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.alter_column('comment_cont',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=280),
               existing_nullable=False)
        batch_op.drop_constraint('Comment_parentId_fkey', type_='foreignkey')
        batch_op.drop_column('parentId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parentId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('Comment_parentId_fkey', 'Comment', ['parentId'], ['id'])
        batch_op.alter_column('comment_cont',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    op.drop_table('Rating')
    # ### end Alembic commands ###
